---
language: go
sudo: false
notifications:
    email: false
go:
  - 1.6
  - 1.7
  - tip
install: make deps
script: make validate && make test
after_success:
  - bash <(curl -s https://codecov.io/bash)